version: '3.4'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'event:5:1,test:4:1'
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
      POSTGRES_DB: kafka_db
    ports:
      - 5432:5432